### ISSUE TITLE
Group should be optional

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-deployer-cloudfoundry#32] opened 2016-04-28 17:11 UTC
Or maybe not even explicit (should be the concern of the caller).

**Comment by markfisher** [comment] 2016-04-28 17:34
"group" could be a first class concept within the Deployer SPI if we want to extend some functionality, such as checking the status of a group of apps or managing the lifecycle of a group of apps... otherwise, we might end up with several different callers managing those concerns

**Comment by gregturn** [comment] 2016-04-28 20:22
Duplicate of https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/pull/19

**Comment by sabbyanandan** [comment] 2016-05-04 15:59
This is already addressed via: #19

**Closed by sabbyanandan** 2016-05-04 15:59 UTC
Labels: in pr
