### ISSUE TITLE
The /tmp folder grows in size even with "autoDeleteMavenArtifacts" set to true

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-cloudfoundry#326] opened 2019-11-15 17:00 UTC
As a user, with `autoDeleteMavenArtifacts` is set to `true`, I see that the artifacts from the `.m2` cache is automatically deleted; however, I still see the uber-jar's present under the app-container's `/tmp` folder. If this continues to grow, we will still run into the same problems reported via https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/issues/322.

To reproduce it, 

1) deploy the following stream in SCDF 2.3 RC1

> stream create --definition "time | log" --name test-stream --deploy

2) SSH into the SCDF-container, and verify `~/.m2` folder

3) SSH into the SCDF-container, and verify `~/tmp` folder

**Comment by dturanski** [comment] 2019-11-18 14:06
I can't reproduce this behavior in our PCF 2.5 test environment, simply by
`stream create ticktock --definition "time | log" --deploy`

**Comment by dturanski** [comment] 2019-11-18 14:09
The source reporting the issue states `I just SSHed into the Data Flow server container to test tasks but before even trying to create a task, I can see what appear to be .jar files for time and log. in ~/tmp` I take this to mean that the app jars are in the `Data Flow` container, which is strange since deployed jars are downloaded to the `Skipper` container.  I don't see any jars in `/tmp` in either container.

**Comment by mheath** [comment] 2019-11-18 18:10
The jar files are not left in `/tmp` but rather `~/tmp` on the SCDF container. I thought it was strange too since I wasn't expecting Data Flow to download any app jars.

**Comment by dturanski** [comment] 2019-11-18 21:01
@mheath  - Thanks for the clarification. I do see some package files in there but not jars.  e.g. 
```
vcap@16291ded-adc7-4ffc-729b-1a24:~/tmp$ ls -l
total 0
drwx------ 2 vcap vcap 32 Nov 18 13:56 streampackages1650842732656636471
drwx------ 3 vcap vcap 54 Nov 18 20:55 streampackages5853668695928037878
drwx------ 2 vcap vcap 32 Oct 29 13:25 streampackages5894768019929801666
drwx------ 2 vcap vcap 32 Oct 29 13:30 streampackages6434276864061552373
drwxr-xr-x 3 vcap vcap 18 Oct 29 13:00 tomcat.5024846052088571970.8080
drwxr-xr-x 2 vcap vcap  6 Oct 29 13:00 tomcat-docbase.6051693671518762080.8080
``` . The stream package directories do accumulate a new one for each deploy, so we need to look at that.  Small files though. 
```
vcap@16291ded-adc7-4ffc-729b-1a24:~/tmp$ ls -lh streampackages1650842732656636471
total 8.0K
-rw-r--r-- 1 vcap vcap 4.1K Nov 18 13:56 ticktock-1.0.0.zip
```

**Comment by dturanski** [comment] 2019-11-18 21:03
I do see them in the skipper container though :)

**Comment by dturanski** [comment] 2019-11-19 16:56
@mheath - Here's what we're seeing. The cf-java-client copies the downloaded jar to a temporary staging file  during deployment https://github.com/cloudfoundry/cf-java-client/blob/d0cea2e676b4351fc52ac641997882f92ed41e00/cloudfoundry-util/src/main/java/org/cloudfoundry/util/FileUtils.java#L83 .  Following a successful push, the staging file is deleted. If there is an error, for example, a service binding fails, the app remains in the `stopped` state and the staging file is not cleaned up.  This may be considered a bug in cf-java-client but if the app cannot start, the user has bigger problems to deal with. So I don't consider it critical to SCDF.  You may also see the files if the deployment is taking some time.  LMK if you are see these files following a successful deployment.

**Comment by mheath** [comment] 2019-11-19 18:18
Here's a copy of the output of what I'm seeing on `red`:
```
vcap@f171249f-be58-4282-595c-c6c4:~/tmp$ ls
spring-cloud-deployer1007595753949180304  streampackages3964563055286692700
spring-cloud-deployer1950664430780692536  streampackages4642921176311541321
spring-cloud-deployer197094299684825517   streampackages5737570506359218636
spring-cloud-deployer374096059078495374   tomcat.7477195199673572028.8080
spring-cloud-deployer5987865051787390164  tomcat-docbase.713226685640609982.8080
spring-cloud-deployer7690186453814982215
vcap@f171249f-be58-4282-595c-c6c4:~/tmp$ ls -l spring-cloud-deployer1007595753949180304
total 36120
-rw-r--r-- 1 vcap vcap 36985112 Nov 18 17:58 33c6ba43215224b73cb3b8aff2d33af4819409fa-timesourcerabbit210RELEASEjar
vcap@f171249f-be58-4282-595c-c6c4:~/tmp$ ls streampackages3964563055286692700/
ticktock2-1.0.0.zip
```

**Comment by jvalkeal** [comment] 2019-11-19 18:38
This are package manifest files uploaded from dataflow to skipper.
```
tmp/streampackages6706661536016868369
tmp/streampackages6706661536016868369/janne-ticktock-1.0.0.zip
vcap@b822d435-4f47-4e0b-4002-5730:~$ unzip -l tmp/streampackages6706661536016868369/janne-ticktock-1.0.0.zip
Archive:  tmp/streampackages6706661536016868369/janne-ticktock-1.0.0.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
      381  2019-11-19 17:14   janne-ticktock-1.0.0/package.yml
        0  2019-11-19 17:14   janne-ticktock-1.0.0/packages/
        0  2019-11-19 17:14   janne-ticktock-1.0.0/packages/log/
      364  2019-11-19 17:14   janne-ticktock-1.0.0/packages/log/package.yml
      870  2019-11-19 17:14   janne-ticktock-1.0.0/packages/log/values.yml
        0  2019-11-19 17:14   janne-ticktock-1.0.0/packages/log/templates/
      594  2019-11-19 17:14   janne-ticktock-1.0.0/packages/log/templates/log.yml
        0  2019-11-19 17:14   janne-ticktock-1.0.0/packages/time/
      365  2019-11-19 17:14   janne-ticktock-1.0.0/packages/time/package.yml
      898  2019-11-19 17:14   janne-ticktock-1.0.0/packages/time/values.yml
        0  2019-11-19 17:14   janne-ticktock-1.0.0/packages/time/templates/
      594  2019-11-19 17:14   janne-ticktock-1.0.0/packages/time/templates/time.yml
---------                     -------
     4066                     12 files
```
Fortunately those are small files but should see if we can clean those after use.

**Comment by dturanski** [comment] 2019-11-19 18:40
@jvalkeal - What about the `spring-cloud-deployernnnnn` ?

**Comment by dturanski** [comment] 2019-11-19 18:50
@mheath -  I see this in v2.0.5 of Local deployer https://github.com/spring-cloud/spring-cloud-deployer-local/blob/v2.0.5.RELEASE/spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalAppDeployer.java#L85 .  It looks like maybe the local deployer is enabled in SCDF.  This might happen if the `cloud` profile is not set.  In my manifest I have 
```
env:
    SPRING_APPLICATION_NAME: dataflow-server
    SPRING_PROFILES_ACTIVE: cloud
    JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{enabled: false}'  ```

**Comment by mheath** [comment] 2019-11-19 18:59
The `cloud` profile gets enabled automatically by the Java buildpack. Just
to be sure, I set `SPRING_PROFILES_ACTIVE` explicitly and still see the
same behavior after restarting Data Flow.

**Comment by dturanski** [comment] 2019-11-19 19:02
We use `java-cfenv` so disable JBP reconfiguration and set the profile explicitly https://dataflow.spring.io/docs/2.3.0.SNAPSHOT/installation/cloudfoundry/cf-cli/.  But I commented out those env and re deployed and did not see what you are seeing anyway.

**Comment by mheath** [comment] 2019-11-19 19:06
Just for giggles, I remove the write permission on the `tmp` directory. Based on the stack trace, the error is happening in the `BootApplicationConfigurationMetadataResolver`. Pardon my ignorance but is this independent of the deployer?

Here's the stack trace:
```
   2019-11-19T12:00:44.38-0700 [APP/PROC/WEB/0] OUT java.lang.RuntimeException: Failed to resolve application resource: URL [http://repo.spring.io/release/org/springframework/cloud/stream/app/log-sink-rabbit/2.1.0.RELEASE/log-sink-rabbit-2.1.0.RELEASE.jar]
   2019-11-19T12:00:44.38-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.configuration.metadata.BootApplicationConfigurationMetadataResolver.listProperties(BootApplicationConfigurationMetadataResolver.java:116)
   2019-11-19T12:00:44.38-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.controller.WhitelistProperties.qualifyProperties(WhitelistProperties.java:62)
   2019-11-19T12:00:44.38-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.service.impl.AppDeploymentRequestCreator.mergeAndExpandAppProperties(AppDeploymentRequestCreator.java:306)
   2019-11-19T12:00:44.38-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.service.impl.AppDeploymentRequestCreator.createRequests(AppDeploymentRequestCreator.java:207)
   2019-11-19T12:00:44.38-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.service.impl.DefaultStreamService.doDeployStream(DefaultStreamService.java:150)
   2019-11-19T12:00:44.38-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.service.impl.DefaultStreamService.deployStream(DefaultStreamService.java:426)
   2019-11-19T12:00:44.38-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.service.impl.DefaultStreamService.createStream(DefaultStreamService.java:385)
   2019-11-19T12:00:44.38-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.service.impl.DefaultStreamService$$FastClassBySpringCGLIB$$89697014.invoke(<generated>)
   2019-11-19T12:00:44.38-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
   2019-11-19T12:00:44.38-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:750)
   2019-11-19T12:00:44.38-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
   2019-11-19T12:00:44.38-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295)
   2019-11-19T12:00:44.38-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
   2019-11-19T12:00:44.38-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
   2019-11-19T12:00:44.38-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
   2019-11-19T12:00:44.38-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.service.impl.DefaultStreamService$$EnhancerBySpringCGLIB$$b72efc01.createStream(<generated>)
   2019-11-19T12:00:44.38-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.controller.StreamDefinitionController.save(StreamDefinitionController.java:121)
...
```

**Comment by dturanski** [comment] 2019-11-19 19:32
I would think this is independent of the deployer. I wonder why @jvalkeal and I are not seeing the same behavior.

**Comment by dturanski** [comment] 2019-11-19 20:17
For the record, it's because of registering the apps via `http`:  
```
app import --uri https://repo.spring.io/libs-release/org/springframework/cloud/stream/app/spring-cloud-stream-app-descriptor/Einstein.RELEASE/spring-cloud-stream-app-descriptor-Einstein.RELEASE.rabbit-apps-maven-repo-url.properties
```

Still investigating...

**Comment by mheath** [comment] 2019-11-19 20:56
If I register the apps using `app import --uri https://dataflow.spring.io/rabbitmq-maven-latest`, I no longer see `spring-cloud-deployer*` directories accumulating in `~/tmp`.

If you want to keep troubleshooting on the OSS side, that's fine but I'm happy to close this issue and get a tile release out.

**Comment by dturanski** [comment] 2019-11-19 21:39
Closing this. Will create a new issue related to the http resources.

**Closed by dturanski** 2019-11-19 21:39 UTC
Labels: backport-2.0.x, bug
