### ISSUE TITLE
Investigate why passing of common app properties are not passed to individual apps

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-deployer-cloudfoundry#155] opened 2017-02-19 16:00 UTC
While using the SCDF CF server, setting the environment variables

```SPRING_APPLICATION_JSON '{"spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.brokers": "104.197.83.4:9092", "spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.zkNodes": "104.197.83.4:2181"}'```

before launching the server, does not result in the deployed applications in a stream getting the properties set, e.g. `spring.cloud.stream.kafka.binder.brokers`.  

As a note, passing them in during deployment does work.

```stream deploy ticktock2 --properties "app.*.spring.cloud.stream.kafka.binder.brokers=104.197.83.4:9092,app.*.spring.cloud.stream.kafka.binder.zkNodes=104.197.83.4:2181"```

**Comment by ilayaperumalg** [comment] 2017-02-20 15:45
At least I could verify that the common application properties are set correctly when setting as `cmdline` args to the SCDF CF server. Hence, it might be that `SPRING_APPLICATION_JSON` is not set for the SCDF environment?

Also, I believe this issue should be moved to https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/issues

**Comment by markpollack** [comment] 2017-02-21 15:54
The server doesn't add any code, so the problem, if any, is in this code base.

**Comment by ericbottard** [comment] 2017-02-21 16:15
Could not reproduce. Here is what I got for one of the apps of my stream:
```
User-Provided:
SPRING_APPLICATION_JSON: {"spring.cloud.stream.bindings.output.destination":"foo.http","spring.cloud.stream.kafka.binder.zkNodes":"104.197.83.4:2181","spring.cloud.stream.bindings.output.producer.requiredGroups":"foo","spring.cloud.stream.kafka.binder.brokers":"104.197.83.4:9092"}
SPRING_CLOUD_APPLICATION_GROUP: foo
```

Closing as invalid

**Closed by ericbottard** 2017-02-21 16:15 UTC
Labels: ready
